#!/usr/bin/env python3
"""Capture a real HAP Pair Setup (SRP-6a) trace from aiohomekit.

Drives a full Pair Setup against a real HomeKit accessory and records:
  * the M1..M6 TLV8 wire messages (the request/response bodies), and
  * the SRP-6a intermediates (salt, A, B, k, x, u, S, K, client proof M1).

Outputs go to test-vectors/pair-setup/ and test-vectors/srp/ with manifests.
The pairing credentials (secret) are saved to a LOCAL gitignored file so the
same pairing can be reused for later milestones (M3 Pair Verify, M4 transport).

The 8-digit setup code is a SECRET: pass --code or set HAP_SETUP_CODE; it is
never written to any output. Verified against aiohomekit 3.2.x.

See docs/runbooks/m2-capture-pair-setup-lifx.md.
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import os
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[3]
PAIR_DIR = REPO / "test-vectors" / "pair-setup"
SRP_DIR = REPO / "test-vectors" / "srp"
PAIRING_SECRET = pathlib.Path(__file__).resolve().parent / "pairing.local.json"

# Captured wire frames: list of dicts {state:int|None, dir:str, bytes:bytes}.
WIRE: list[dict] = []
# Captured SrpClient instances (the one used for pairing is the last).
SRP: list = []


def _install_probes() -> None:
    """Monkeypatch aiohomekit's TLV codec + SrpClient to tee the trace."""
    from aiohomekit.protocol.tlv import TLV

    orig_encode = TLV.encode_list
    orig_decode = TLV.decode_bytes

    def _state_of(pairs) -> int | None:
        for t, v in pairs:
            if t == TLV.kTLVType_State:
                return int(bytes(v)[0])
        return None

    def encode_list(d):
        out = orig_encode(d)
        WIRE.append({"state": _state_of(d), "dir": "request", "bytes": bytes(out)})
        return out

    def decode_bytes(bs, expected=None):
        res = orig_decode(bs, expected)
        WIRE.append({"state": _state_of(res), "dir": "response", "bytes": bytes(bs)})
        return res

    TLV.encode_list = staticmethod(encode_list)
    TLV.decode_bytes = staticmethod(decode_bytes)

    from aiohomekit.crypto.srp import SrpClient

    orig_set_spk = SrpClient.set_server_public_key

    def set_server_public_key(self, B_b):
        SRP.append(self)
        return orig_set_spk(self, B_b)

    SrpClient.set_server_public_key = set_server_public_key


async def _run_pairing(device_id: str, pin: str, alias: str):
    from aiohomekit import Controller
    from aiohomekit.zeroconf import ZeroconfServiceListener
    from zeroconf.asyncio import AsyncServiceBrowser, AsyncZeroconf

    async with AsyncZeroconf() as azc:
        controller = Controller(async_zeroconf_instance=azc)
        # A browser for the HAP service types must exist before the controller
        # starts (it looks one up via find_brower_for_hap_type).
        browser = AsyncServiceBrowser(
            azc.zeroconf,
            ["_hap._tcp.local.", "_hap._udp.local."],
            listener=ZeroconfServiceListener(),
        )
        async with controller:
            discovery = await controller.async_find(device_id)
            finish = await discovery.async_start_pairing(alias)
            pairing = await finish(pin)
            # Persist the (secret) pairing data locally for reuse in later milestones.
            controller.save_data(str(PAIRING_SECRET))
        await browser.async_cancel()
        return pairing


def _be(n: int, length: int) -> bytes:
    return int(n).to_bytes(length, "big")


def _write(path: pathlib.Path, data: bytes) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return len(data)


def _toml_table(rows: list[tuple[str, str, int, str]]) -> str:
    out = ["# Generated by capture_pair_setup.py - do not edit by hand.\n"]
    for vid, fname, length, note in rows:
        out.append("[[vector]]")
        out.append(f'id = "{vid}"')
        out.append(f'file = "{fname}"')
        out.append(f"len = {length}")
        if note:
            out.append(f'note = "{note}"')
        out.append("")
    return "\n".join(out)


def _emit_outputs() -> int:
    warnings = 0

    # --- Wire messages M1..M6 (first occurrence of each state) ---
    by_state: dict[int, dict] = {}
    for f in WIRE:
        st = f["state"]
        if st in (1, 2, 3, 4, 5, 6) and st not in by_state:
            by_state[st] = f
    pair_rows = []
    for st in range(1, 7):
        frame = by_state.get(st)
        fname = f"m{st}.bin"
        if frame is None:
            print(f"  WARNING: M{st} wire message not captured", file=sys.stderr)
            warnings += 1
            continue
        n = _write(PAIR_DIR / fname, frame["bytes"])
        pair_rows.append((f"m{st}", fname, n, frame["dir"]))
        print(f"  pair-setup/{fname}: {n} bytes ({frame['dir']}, state M{st})")
    _write(PAIR_DIR / "manifest.toml", _toml_table(pair_rows).encode())

    # --- SRP intermediates ---
    srp_rows = []
    if not SRP:
        print("  WARNING: no SrpClient captured; SRP intermediates unavailable", file=sys.stderr)
        warnings += 1
    else:
        c = SRP[-1]
        try:
            u_val = c._calculate_u()
        except Exception:  # noqa: BLE001 - best-effort intermediate
            u_val = None
        # 3072-bit group => 384-byte field; SHA-512 => 64-byte digests.
        # k = H(N | PAD(g)) is a group constant; compute it canonically rather
        # than reading c.k (which has been observed to read back wrong after the
        # full M5/M6 exchange). Self-check against c.k and warn on divergence.
        n_len = len(bytes(c.B_b))
        n_bytes = int(c.n).to_bytes(n_len, "big")
        g_bytes = (b"\x00" * (n_len - 1)) + bytes([int(c.g)])
        k_canon = hashlib.sha512(n_bytes + g_bytes).digest()
        if k_canon != _be(c.k, 64):
            print("  note: c.k != canonical H(N|PAD(g)); writing canonical k", file=sys.stderr)
        items = {
            "salt": (bytes(c.salt_b), "Pair-Setup salt (16B)"),
            "A": (bytes(c.A_b), "client public key (384B)"),
            "B": (bytes(c.B_b), "accessory public key (384B)"),
            "k": (k_canon, "k = H(N | PAD(g))"),
            "x": (_be(c.x, 64), "x = H(s | H(I:P))"),
            "S": (_be(c.get_shared_secret(), 384), "premaster secret (sensitive)"),
            "K": (bytes(c.get_session_key_bytes()), "session key H(S) (sensitive)"),
            "proof_m1": (bytes(c.get_proof_bytes()), "client proof M1 (sensitive)"),
        }
        if u_val is not None:
            items["u"] = (_be(u_val, 64), "u = H(PAD(A) | PAD(B))")
        for name, (data, note) in items.items():
            n = _write(SRP_DIR / f"{name}.bin", data)
            srp_rows.append((name, f"{name}.bin", n, note))
            print(f"  srp/{name}.bin: {n} bytes")
    _write(SRP_DIR / "manifest.toml", _toml_table(srp_rows).encode())

    return warnings


def main() -> int:
    ap = argparse.ArgumentParser(description="Capture a real HAP Pair Setup (SRP-6a) trace from aiohomekit.")
    ap.add_argument("--device", help="HAP device id of the target accessory (from _hap._tcp discovery).")
    ap.add_argument("--ip", help="(unused; --device preferred)")
    ap.add_argument("--code", help="8-digit setup code XXX-XX-XXX. SECRET - prefer HAP_SETUP_CODE env.")
    ap.add_argument("--alias", default="hap-rust-test", help="local alias for the pairing.")
    ap.add_argument("--dry-run", action="store_true", help="Validate imports/instrumentation; no pairing.")
    args = ap.parse_args()

    if not args.device:
        ap.error("specify --device <hap-device-id> (from _hap._tcp discovery)")

    code = args.code or os.environ.get("HAP_SETUP_CODE")
    if not code:
        ap.error("no setup code: pass --code or set HAP_SETUP_CODE (a SECRET; never commit it)")
    digits = code.replace("-", "")
    if len(digits) != 8 or not digits.isdigit():
        ap.error("setup code must be 8 digits (XXX-XX-XXX)")
    pin = f"{digits[0:3]}-{digits[3:5]}-{digits[5:8]}"

    _install_probes()
    print("instrumentation installed (TLV.encode_list/decode_bytes, SrpClient.set_server_public_key)")

    if args.dry_run:
        print("dry-run OK: imports + probes attach cleanly; not pairing.")
        return 0

    print(f"pairing with device {args.device} (alias {args.alias}) ...")
    asyncio.run(_run_pairing(args.device, pin, args.alias))
    print("pair setup complete.")

    warnings = _emit_outputs()
    print(f"\npairing credentials saved (LOCAL, gitignored): {PAIRING_SECRET}")
    print("SAFE TO COMMIT: pair-setup/m1..m6.bin + manifest; srp/{salt,A,B,k,x,u}.bin + manifest")
    print("SENSITIVE (review before commit): srp/{S,K,proof_m1}.bin; m5/m6 carry the encrypted LTPK exchange")
    print("NEVER COMMIT: the setup code; pairing.local.json (controller long-term secret)")
    if warnings:
        print(f"\n{warnings} warning(s) - see above.", file=sys.stderr)
        return 2
    print("\nNo warnings: all wire messages and SRP intermediates captured.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
