//! Generate `crates/hap-model/src/generated.rs` from the curated type table.
//!
//! Reads the hand-curated `xtask/model/hap-types.json` (short HAP UUIDs, Rust
//! names, and per-characteristic default formats) and emits the `ServiceType`
//! and `CharacteristicType` enums with short→full UUID expansion, a `from_uuid`
//! lookup, a `uuid` accessor, and `default_format`. The generated file is
//! committed so downstream crates build without running `xtask`.

use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::Deserialize;

#[derive(Deserialize)]
struct Table {
    services: Vec<TypeEntry>,
    characteristics: Vec<TypeEntry>,
}

#[derive(Deserialize)]
struct TypeEntry {
    name: String,
    short: String,
    #[serde(default)]
    format: Option<String>,
    #[serde(default)]
    unit: Option<String>,
    /// `[[value, "Name"], ...]` for enumerated characteristics.
    #[serde(default)]
    valid_values: Vec<(i64, String)>,
}

fn full_uuid(short: &str) -> String {
    let padded = format!("{:0>8}", short.to_ascii_lowercase());
    format!("{padded}-0000-1000-8000-0026bb765291")
}

fn unit_variant(unit: &str) -> &'static str {
    match unit {
        "celsius" => "Celsius",
        "percentage" => "Percentage",
        "arcdegrees" => "ArcDegrees",
        "lux" => "Lux",
        "seconds" => "Seconds",
        "ppm" => "Ppm",
        "micrograms/m^3" => "MicrogramsPerM3",
        other => panic!("unknown unit {other:?} in hap-types.json"),
    }
}

fn format_variant(fmt: &str) -> &'static str {
    match fmt {
        "bool" => "Bool",
        "uint8" => "Uint8",
        "uint16" => "Uint16",
        "uint32" => "Uint32",
        "uint64" => "Uint64",
        "int" => "Int",
        "float" => "Float",
        "string" => "String",
        "tlv8" => "Tlv8",
        "data" => "Data",
        other => panic!("unknown format {other:?} in hap-types.json"),
    }
}

/// Regenerate `crates/hap-model/src/generated.rs`. Returns the written path.
///
/// # Errors
/// Fails if the workspace root cannot be located, the curated
/// `xtask/model/hap-types.json` cannot be read or parsed, or the output file
/// cannot be written.
pub(crate) fn run() -> Result<String> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .context("xtask has no parent directory")?
        .to_path_buf();
    let table_path = root.join("xtask/model/hap-types.json");
    let bytes =
        std::fs::read(&table_path).with_context(|| format!("reading {}", table_path.display()))?;
    let table: Table = serde_json::from_slice(&bytes)
        .with_context(|| format!("parsing {}", table_path.display()))?;

    let mut s = String::new();
    s.push_str(
        "// @generated by `cargo xtask codegen-hap-types` from xtask/model/hap-types.json.\n",
    );
    s.push_str("// Do not edit by hand. Re-run the codegen command to regenerate.\n\n");
    // Generated match tables legitimately repeat values across arms, when the
    // curated JSON has no data for a method the match collapses to a single `_ =>
    // None` arm, and the expanded full-catalog impl blocks exceed 100 lines —
    // all patterns are noise on machine-emitted code.
    s.push_str("#![allow(clippy::match_same_arms, clippy::match_single_binding, clippy::too_many_lines)]\n\n");
    s.push_str("use crate::uuid::Uuid;\n");
    s.push_str("#[allow(unused_imports)]\nuse crate::format::CharFormat;\n\n");
    s.push_str("#[allow(unused_imports)]\nuse crate::unit::Unit;\n\n");

    emit_enum(&mut s, "ServiceType", &table.services, false);
    emit_enum(&mut s, "CharacteristicType", &table.characteristics, true);

    let out = root.join("crates/hap-model/src/generated.rs");
    std::fs::write(&out, s).with_context(|| format!("writing {}", out.display()))?;
    Ok(out.display().to_string())
}

#[allow(clippy::too_many_lines)]
fn emit_enum(s: &mut String, name: &str, entries: &[TypeEntry], with_format: bool) {
    let _ = writeln!(
        s,
        "/// HAP-defined {name} (generated). `Unknown` carries any non-HAP UUID."
    );
    let _ = writeln!(s, "#[derive(Debug, Clone, PartialEq, Eq, Hash)]");
    let _ = writeln!(s, "#[non_exhaustive]");
    let _ = writeln!(s, "pub enum {name} {{");
    for e in entries {
        let _ = writeln!(s, "    /// HAP short type {:?}.", e.short);
        let _ = writeln!(s, "    {},", e.name);
    }
    let _ = writeln!(s, "    /// A type not in the generated table.");
    let _ = writeln!(s, "    Unknown(Uuid),");
    let _ = writeln!(s, "}}\n");

    let _ = writeln!(s, "impl {name} {{");
    // from_uuid
    let _ = writeln!(
        s,
        "    /// Map a parsed [`Uuid`] to its named variant, or `Unknown`."
    );
    let _ = writeln!(s, "    pub fn from_uuid(u: &Uuid) -> Self {{");
    let _ = writeln!(s, "        match u.as_full() {{");
    for e in entries {
        let _ = writeln!(
            s,
            "            {:?} => Self::{},",
            full_uuid(&e.short),
            e.name
        );
    }
    let _ = writeln!(s, "            _ => Self::Unknown(u.clone()),");
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}\n");
    // uuid()
    let _ = writeln!(s, "    /// The canonical [`Uuid`] for this type.");
    let _ = writeln!(s, "    pub fn uuid(&self) -> Uuid {{");
    let _ = writeln!(s, "        match self {{");
    for e in entries {
        let _ = writeln!(
            s,
            "            Self::{} => Uuid::from_full_unchecked({:?}.to_string()),",
            e.name,
            full_uuid(&e.short)
        );
    }
    let _ = writeln!(s, "            Self::Unknown(u) => u.clone(),");
    let _ = writeln!(s, "        }}");
    let _ = writeln!(s, "    }}");

    if with_format {
        let _ = writeln!(
            s,
            "\n    /// The HAP default value format for this characteristic, if known."
        );
        let _ = writeln!(
            s,
            "    pub fn default_format(&self) -> Option<CharFormat> {{"
        );
        let _ = writeln!(s, "        match self {{");
        for e in entries {
            if let Some(fmt) = &e.format {
                let _ = writeln!(
                    s,
                    "            Self::{} => Some(CharFormat::{}),",
                    e.name,
                    format_variant(fmt)
                );
            }
        }
        let _ = writeln!(s, "            _ => None,");
        let _ = writeln!(s, "        }}");
        let _ = writeln!(s, "    }}");

        // unit()
        let _ = writeln!(
            s,
            "\n    /// The HAP unit for this characteristic, if it has one."
        );
        let _ = writeln!(s, "    pub fn unit(&self) -> Option<Unit> {{");
        let _ = writeln!(s, "        match self {{");
        for e in entries {
            if let Some(u) = &e.unit {
                let _ = writeln!(
                    s,
                    "            Self::{} => Some(Unit::{}),",
                    e.name,
                    unit_variant(u)
                );
            }
        }
        let _ = writeln!(s, "            _ => None,");
        let _ = writeln!(s, "        }}");
        let _ = writeln!(s, "    }}");

        // valid_values()
        let _ = writeln!(
            s,
            "\n    /// Named enum values for an enumerated characteristic, smallest-first."
        );
        let _ = writeln!(
            s,
            "    pub fn valid_values(&self) -> Option<&'static [(i64, &'static str)]> {{"
        );
        let _ = writeln!(s, "        match self {{");
        for e in entries {
            if !e.valid_values.is_empty() {
                let pairs: Vec<String> = e
                    .valid_values
                    .iter()
                    .map(|(v, n)| format!("({v}, {n:?})"))
                    .collect();
                let _ = writeln!(
                    s,
                    "            Self::{} => Some(&[{}]),",
                    e.name,
                    pairs.join(", ")
                );
            }
        }
        let _ = writeln!(s, "            _ => None,");
        let _ = writeln!(s, "        }}");
        let _ = writeln!(s, "    }}");
    }

    let _ = writeln!(s, "}}\n");
}
