//! Integration tests for `SetupPayload::parse` against Python-generated oracle vectors.

// CLAUDE.md test-code carve-out.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use hap_controller::SetupPayload;

#[test]
fn decodes_known_vectors() {
    // Vector 1: bridge (category=2), setup_code=51808582, setup_id="7OSX"
    // Generated by: encode(51808582, 2, "7OSX") → "X-HM://0024BRZUU7OSX"
    let p = SetupPayload::parse("X-HM://0024BRZUU7OSX").unwrap();
    assert_eq!(p.setup_code, "51808582");
    assert_eq!(p.category, 2);
    assert!(p.flags.ip);
    assert!(!p.flags.ble);
    assert!(!p.flags.nfc);
    assert_eq!(p.setup_id.as_deref(), Some("7OSX"));

    // Vector 2: lightbulb (category=5), setup_code=11122333, setup_id="ABCD"
    // Generated by: encode(11122333, 5, "ABCD") → "X-HM://00527813XABCD"
    let q = SetupPayload::parse("X-HM://00527813XABCD").unwrap();
    assert_eq!(q.setup_code, "11122333");
    assert_eq!(q.category, 5);
    assert!(q.flags.ip);
    assert_eq!(q.setup_id.as_deref(), Some("ABCD"));
}

#[test]
fn no_setup_id() {
    // Parse a payload without the optional 4-char setup id.
    let p = SetupPayload::parse("X-HM://0024BRZUU").unwrap();
    assert_eq!(p.setup_code, "51808582");
    assert_eq!(p.category, 2);
    assert!(p.setup_id.is_none());
}

#[test]
fn rejects_non_xhm() {
    assert!(matches!(
        SetupPayload::parse("https://example.com").unwrap_err(),
        hap_controller::HapError::InvalidSetupPayload
    ));
}

#[test]
fn rejects_too_short() {
    assert!(matches!(
        SetupPayload::parse("X-HM://12345").unwrap_err(),
        hap_controller::HapError::InvalidSetupPayload
    ));
}

#[test]
fn rejects_invalid_base36() {
    // '!' is not a valid base-36 character.
    assert!(matches!(
        SetupPayload::parse("X-HM://!!!!!!!!! ").unwrap_err(),
        hap_controller::HapError::InvalidSetupPayload
    ));
}
