//! Integration tests for `SetupPayload::parse` against Python-generated oracle vectors.

// CLAUDE.md test-code carve-out.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use hap_controller::SetupPayload;

#[test]
fn decodes_known_vectors() {
    // Vector 1: bridge (category=2), setup_code=51808582, setup_id="7OSX"
    // Generated by: encode(51808582, 2, "7OSX") → "X-HM://0024BRZUU7OSX"
    let p = SetupPayload::parse("X-HM://0024BRZUU7OSX").unwrap();
    assert_eq!(p.setup_code, "51808582");
    assert_eq!(p.category, 2);
    assert!(p.flags.ip);
    assert!(!p.flags.ble);
    assert!(!p.flags.nfc);
    assert_eq!(p.setup_id.as_deref(), Some("7OSX"));

    // Vector 2: lightbulb (category=5), setup_code=11122333, setup_id="ABCD"
    // Generated by: encode(11122333, 5, "ABCD") → "X-HM://00527813XABCD"
    let q = SetupPayload::parse("X-HM://00527813XABCD").unwrap();
    assert_eq!(q.setup_code, "11122333");
    assert_eq!(q.category, 5);
    assert!(q.flags.ip);
    assert_eq!(q.setup_id.as_deref(), Some("ABCD"));
}

#[test]
fn no_setup_id() {
    // Parse a payload without the optional 4-char setup id.
    let p = SetupPayload::parse("X-HM://0024BRZUU").unwrap();
    assert_eq!(p.setup_code, "51808582");
    assert_eq!(p.category, 2);
    assert!(p.setup_id.is_none());
}

#[test]
fn rejects_non_xhm() {
    assert!(matches!(
        SetupPayload::parse("https://example.com").unwrap_err(),
        hap_controller::HapError::InvalidSetupPayload
    ));
}

#[test]
fn rejects_too_short() {
    assert!(matches!(
        SetupPayload::parse("X-HM://12345").unwrap_err(),
        hap_controller::HapError::InvalidSetupPayload
    ));
}

#[test]
fn rejects_invalid_base36() {
    // '!' is not a valid base-36 character.
    assert!(matches!(
        SetupPayload::parse("X-HM://!!!!!!!!! ").unwrap_err(),
        hap_controller::HapError::InvalidSetupPayload
    ));
}

#[test]
fn decodes_ble_and_nfc_flags() {
    // Encode a payload with a chosen flag nibble, then assert the decode.
    // Layout: [category:8][flags:4][setup_code:27] within the 9-char base-36.
    // This is a round-trip against our own encode/decode bit assumptions for
    // the ble/nfc bits (unlike vectors 1/2 above, not cross-checked against
    // an independently captured vector). Flag bits: ip=0x2, ble=0x4, nfc=0x8.
    fn encode(setup_code: u32, category: u16, flags: u8, setup_id: &str) -> String {
        let value: u64 = ((u64::from(category)) << 31)
            | ((u64::from(flags) & 0xF) << 27)
            | u64::from(setup_code & 0x7FF_FFFF);
        let base36 = to_base36_9(value);
        format!("X-HM://{base36}{setup_id}")
    }
    fn to_base36_9(mut v: u64) -> String {
        const D: &[u8; 36] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        let mut buf = [b'0'; 9];
        for i in (0..9).rev() {
            buf[i] = D[(v % 36) as usize];
            v /= 36;
        }
        String::from_utf8(buf.to_vec()).unwrap()
    }

    // ip only (0x2)
    let p = SetupPayload::parse(&encode(11_122_333, 5, 0x2, "ABCD")).unwrap();
    assert!(p.flags.ip && !p.flags.ble && !p.flags.nfc);
    // ip + ble (0x6)
    let p = SetupPayload::parse(&encode(11_122_333, 5, 0x6, "ABCD")).unwrap();
    assert!(p.flags.ip && p.flags.ble && !p.flags.nfc);
    // ip + ble + nfc (0xE)
    let p = SetupPayload::parse(&encode(11_122_333, 5, 0xE, "ABCD")).unwrap();
    assert!(p.flags.ip && p.flags.ble && p.flags.nfc);
    // code + category still decode correctly alongside the flags
    assert_eq!(p.setup_code, "11122333");
    assert_eq!(p.category, 5);
}
